apiVersion: shortener.nafine.dev/v1alpha1
kind: UrlShortener
metadata:
  labels:
    app.kubernetes.io/name: shortener-operator
    app.kubernetes.io/managed-by: kustomize
  name: urlshortener-sample
spec:
  replicas: 3
  appEnv: "local"
  storageDsnSecretRef:
      name: storage-dsn
      key: dsn
  apiKeysSecretRef:
      name: keys-secret
      key: apiKeys.yaml
  http:
    port: 8080
    timeout: 4s
    idleTimeout: 10s
